### ISSUE TITLE
undefined function: :gpb_parse.post_process/2

### ISSUE THREAD

**Issue by eraserewind** [bitwalker/exprotobuf#6] opened 2015-01-08 14:06 UTC
Hi, i'm having this issue with exprotobuf 0.8.5 and [the mumble proto](https://github.com/mumble-voip/mumble/blob/master/src/Mumble.proto):

```
== Compilation error on file lib/opnd/mumble/protocol.ex ==
** (UndefinedFunctionError) undefined function: :gpb_parse.post_process/2
    :gpb_parse.post_process([{:package, [:MumbleProto]}, {:option, [:optimize_for], :SPEED}, {{:msg, :Version}, [{:field, :version, 1, :undefined, :uint32, :optional, []}, {:field, :release, 2, :undefined, :string, :optional, []}, {:field, :os, 3, :undefined, :string, :optional, []}, {:field, :os_version, 4, :undefined, :string, :optional, []}]}, {{:msg, :UDPTunnel}, [{:field, :packet, 1, :undefined, :bytes, :required, []}]}, {{:msg, :Authenticate}, [{:field, :username, 1, :undefined, :string, :optional, []}, {:field, :password, 2, :undefined, :string, :optional, []}, {:field, :tokens, 3, :undefined, :string, :repeated, []}, {:field, :celt_versions, 4, :undefined, :int32, :repeated, []}, {:field, :opus, 5, :undefined, :bool, :optional, [default: false]}]}, {{:msg, :Ping}, [{:field, :timestamp, 1, :undefined, :uint64, :optional, []}, {:field, :good, 2, :undefined, :uint32, :optional, []}, {:field, :late, 3, :undefined, :uint32, :optional, []}, {:field, :lost, 4, :undefined, :uint32, :optional, []}, {:field, :resync, 5, :undefined, :uint32, :optional, []}, {:field, :udp_packets, 6, :undefined, :uint32, :optional, []}, {:field, :tcp_packets, 7, :undefined, :uint32, :optional, []}, {:field, :udp_ping_avg, 8, :undefined, :float, :optional, []}, {:field, :udp_ping_var, 9, :undefined, :float, :optional, []}, {:field, :tcp_ping_avg, 10, :undefined, :float, :optional, []}, {:field, :tcp_ping_var, 11, :undefined, :float, :optional, []}]}, {{:msg, :Reject}, [{{:enum, :RejectType}, [None: 0, WrongVersion: 1, InvalidUsername: 2, WrongUserPW: 3, WrongServerPW: 4, UsernameInUse: 5, ServerFull: 6, NoCertificate: 7, AuthenticatorFail: 8]}, {:field, :type, 1, :undefined, {:ref, [:RejectType]}, :optional, []}, {:field, :reason, 2, :undefined, :string, :optional, []}]}, {{:msg, :ServerSync}, [{:field, :session, 1, :undefined, :uint32, :optional, []}, {:field, :max_bandwidth, 2, :undefined, :uint32, :optional, []}, {:field, :welcome_text, 3, :undefined, :string, :optional, []}, {:field, :permissions, 4, :undefined, :uint64, :optional, []}]}, {{:msg, :ChannelRemove}, [{:field, :channel_id, 1, :undefined, :uint32, :required, []}]}, {{:msg, :ChannelState}, [{:field, :channel_id, 1, :undefined, :uint32, :optional, []}, {:field, :parent, 2, :undefined, :uint32, :optional, []}, {:field, :name, 3, :undefined, :string, :optional, []}, {:field, :links, 4, :undefined, :uint32, :repeated, []}, {:field, :description, 5, :undefined, :string, :optional, []}, {:field, :links_add, 6, :undefined, :uint32, :repeated, []}, {:field, :links_remove, 7, :undefined, :uint32, :repeated, []}, {:field, :temporary, 8, :undefined, :bool, :optional, [default: false]}, {:field, :position, 9, :undefined, :int32, :optional, [default: 0]}, {:field, :description_hash, 10, :undefined, :bytes, :optional, []}]}, {{:msg, :UserRemove}, [{:field, :session, 1, :undefined, :uint32, :required, []}, {:field, :actor, 2, :undefined, :uint32, :optional, []}, {:field, :reason, 3, :undefined, :string, :optional, []}, {:field, :ban, 4, :undefined, :bool, :optional, []}]}, {{:msg, :UserState}, [{:field, :session, 1, :undefined, :uint32, :optional, []}, {:field, :actor, 2, :undefined, :uint32, :optional, []}, {:field, :name, 3, :undefined, :string, :optional, []}, {:field, :user_id, 4, :undefined, :uint32, :optional, []}, {:field, :channel_id, 5, :undefined, :uint32, :optional, []}, {:field, :mute, 6, :undefined, :bool, :optional, []}, {:field, :deaf, 7, :undefined, :bool, :optional, []}, {:field, :suppress, 8, :undefined, :bool, :optional, []}, {:field, :self_mute, 9, :undefined, :bool, :optional, []}, {:field, :self_deaf, 10, :undefined, :bool, :optional, []}, {:field, :texture, 11, :undefined, :bytes, :optional, []}, {:field, :plugin_context, 12, :undefined, :bytes, :optional, []}, {:field, :plugin_identity, 13, :undefined, :string, :optional, []}, {:field, :comment, 14, :undefined, :string, :optional, []}, {:field, :hash, 15, :undefined, :string, :optional, []}, {:field, :comment_hash, 16, :undefined, :bytes, :optional, []}, {:field, :texture_hash, 17, :undefined, :bytes, :optional, []}, {:field, :priority_speaker, 18, :undefined, :bool, :optional, []}, {:field, :recording, 19, :undefined, :bool, :optional, []}]}, {{:msg, :BanList}, [{{:msg, :BanEntry}, [{:field, :address, 1, :undefined, :bytes, :required, []}, {:field, :mask, 2, :undefined, :uint32, :required, []}, {:field, :name, 3, :undefined, :string, :optional, []}, {:field, :hash, 4, :undefined, :string, :optional, []}, {:field, :reason, 5, :undefined, :string, :optional, []}, {:field, :start, 6, :undefined, :string, :optional, []}, {:field, :duration, 7, :undefined, :uint32, :optional, []}]}, {:field, :bans, 1, :undefined, {:ref, [:BanEntry]}, :repeated, []}, {:field, :query, 2, :undefined, :bool, :optional, [default: false]}]}, {{:msg, :TextMessage}, [{:field, :actor, 1, :undefined, :uint32, :optional, []}, {:field, :session, 2, :undefined, :uint32, :repeated, []}, {:field, :channel_id, 3, :undefined, :uint32, :repeated, []}, {:field, :tree_id, 4, :undefined, :uint32, :repeated, []}, {:field, :message, 5, :undefined, :string, :required, []}]}, {{:msg, :PermissionDenied}, [{{:enum, :DenyType}, [Text: 0, Permission: 1, SuperUser: 2, ChannelName: 3, TextTooLong: 4, H9K: 5, TemporaryChannel: 6, MissingCertificate: 7, UserName: 8, ChannelFull: 9, NestingLimit: 10]}, {:field, :permission, 1, :undefined, :uint32, :optional, []}, {:field, :channel_id, 2, :undefined, :uint32, :optional, []}, {:field, :session, 3, :undefined, :uint32, :optional, []}, {:field, :reason, 4, :undefined, :string, :optional, []}, {:field, :type, 5, :undefined, {:ref, [:DenyType]}, :optional, []}, {:field, :name, 6, :undefined, :string, :optional, []}]}, {{:msg, :ACL}, [{{:msg, :ChanGroup}, [{:field, :name, 1, :undefined, :string, :required, []}, {:field, :inherited, 2, :undefined, :bool, :optional, [default: true]}, {:field, :inherit, 3, :undefined, :bool, :optional, [default: true]}, {:field, :inheritable, 4, :undefined, :bool, :optional, [default: true]}, {:field, :add, 5, :undefined, :uint32, :repeated, []}, {:field, :remove, 6, :undefined, :uint32, :repeated, []}, {:field, :inherited_members, 7, :undefined, :uint32, :repeated, []}]}, {{:msg, :ChanACL}, [{:field, :apply_here, 1, :undefined, :bool, :optional, [default: true]}, {:field, :apply_subs, 2, :undefined, :bool, :optional, [default: true]}, {:field, :inherited, 3, :undefined, :bool, :optional, [default: true]}, {:field, :user_id, 4, :undefined, :uint32, :optional, []}, {:field, :group, 5, :undefined, :string, :optional, []}, {:field, :grant, 6, :undefined, :uint32, :optional, []}, {:field, :deny, 7, :undefined, :uint32, :optional, []}]}, {:field, :channel_id, 1, :undefined, :uint32, :required, []}, {:field, :inherit_acls, 2, :undefined, :bool, :optional, [default: true]}, {:field, :groups, 3, :undefined, {:ref, [:ChanGroup]}, :repeated, []}, {:field, :acls, 4, :undefined, {:ref, [:ChanACL]}, :repeated, []}, {:field, :query, 5, :undefined, :bool, :optional, [default: false]}]}, {{:msg, :QueryUsers}, [{:field, :ids, 1, :undefined, :uint32, :repeated, []}, {:field, :names, 2, :undefined, :string, :repeated, []}]}, {{:msg, :CryptSetup}, [{:field, :key, 1, :undefined, :bytes, :optional, []}, {:field, :client_nonce, 2, :undefined, :bytes, :optional, []}, {:field, :server_nonce, 3, :undefined, :bytes, :optional, []}]}, {{:msg, :ContextActionModify}, [{{:enum, :Context}, [Server: 1, Channel: 2, User: 4]}, {{:enum, :Operation}, [Add: 0, Remove: 1]}, {:field, :action, 1, :undefined, :string, :required, []}, {:field, :text, 2, :undefined, :string, :optional, []}, {:field, :context, 3, :undefined, :uint32, :optional, []}, {:field, :operation, 4, :undefined, {:ref, [:Operation]}, :optional, []}]}, {{:msg, :ContextAction}, [{:field, :session, 1, :undefined, :uint32, :optional, []}, {:field, :channel_id, 2, :undefined, :uint32, :optional, []}, {:field, :action, 3, :undefined, :string, :required, []}]}, {{:msg, :UserList}, [{{:msg, :User}, [{:field, :user_id, 1, :undefined, :uint32, :required, []}, {:field, :name, 2, :undefined, :string, :optional, []}, {:field, :last_seen, 3, :undefined, :string, :optional, []}, {:field, :last_channel, 4, :undefined, :uint32, :optional, []}]}, {:field, :users, 1, :undefined, {:ref, [:User]}, :repeated, []}]}, {{:msg, :VoiceTarget}, [{{:msg, :Target}, [{:field, :session, 1, :undefined, :uint32, :repeated, []}, {:field, :channel_id, 2, :undefined, :uint32, :optional, []}, {:field, :group, 3, :undefined, :string, :optional, []}, {:field, :links, 4, :undefined, :bool, :optional, [default: false]}, {:field, :children, 5, :undefined, :bool, :optional, [default: false]}]}, {:field, :id, 1, :undefined, :uint32, :optional, []}, {:field, :targets, 2, :undefined, {:ref, [:Target]}, :repeated, []}]}, {{:msg, :PermissionQuery}, [{:field, :channel_id, 1, :undefined, :uint32, :optional, []}, {:field, :permissions, 2, :undefined, :uint32, :optional, []}, {:field, :flush, 3, :undefined, :bool, :optional, [default: false]}]}, {{:msg, :CodecVersion}, [{:field, :alpha, 1, :undefined, :int32, :required, []}, {:field, :beta, 2, :undefined, :int32, :required, []}, {:field, :prefer_alpha, 3, :undefined, :bool, :required, [default: true]}, {:field, :opus, 4, :undefined, :bool, :optional, [default: false]}]}, {{:msg, :UserStats}, [{{:msg, :Stats}, [{:field, :good, 1, :undefined, :uint32, :optional, []}, {:field, :late, 2, :undefined, :uint32, :optional, []}, {:field, :lost, 3, :undefined, :uint32, :optional, []}, {:field, :resync, 4, :undefined, :uint32, :optional, []}]}, {:field, :session, 1, :undefined, :uint32, :optional, []}, {:field, :stats_only, 2, :undefined, :bool, :optional, [default: false]}, {:field, :certificates, 3, :undefined, :bytes, :repeated, []}, {:field, :from_client, 4, :undefined, {:ref, [:Stats]}, :optional, []}, {:field, :from_server, 5, :undefined, {:ref, [:Stats]}, :optional, []}, {:field, :udp_packets, 6, :undefined, :uint32, :optional, []}, {:field, :tcp_packets, 7, :undefined, :uint32, :optional, []}, {:field, :udp_ping_avg, 8, :undefined, :float, :optional, []}, {:field, :udp_ping_var, 9, :undefined, :float, :optional, []}, {:field, :tcp_ping_avg, 10, :undefined, :float, :optional, []}, {:field, :tcp_ping_var, 11, :undefined, :float, :optional, []}, {:field, :version, 12, :undefined, {:ref, [:Version]}, :optional, []}, {:field, :celt_versions, 13, :undefined, :int32, :repeated, []}, {:field, :address, 14, :undefined, :bytes, :optional, []}, {:field, :bandwidth, 15, :undefined, :uint32, :optional, []}, {:field, :onlinesecs, 16, :undefined, :uint32, :optional, []}, {:field, :idlesecs, 17, :undefined, :uint32, :optional, ...}, {:field, :strong_certificate, 18, :undefined, :bool, ...}, {:field, :opus, 19, :undefined, :bool, ...}]}, {{:msg, :RequestBlob}, [{:field, :session_texture, 1, :undefined, :uint32, :repeated, []}, {:field, :session_comment, 2, :undefined, :uint32, :repeated, []}, {:field, :channel_description, 3, :undefined, :uint32, :repeated, []}]}, {{:msg, :ServerConfig}, [{:field, :max_bandwidth, 1, :undefined, :uint32, :optional, []}, {:field, :welcome_text, 2, :undefined, :string, :optional, []}, {:field, :allow_html, 3, :undefined, :bool, :optional, []}, {:field, :message_length, 4, :undefined, :uint32, :optional, []}, {:field, :image_message_length, 5, :undefined, :uint32, :optional, []}]}, {{:msg, :SuggestConfig}, [{:field, :version, 1, :undefined, :uint32, :optional, []}, {:field, :positional, 2, :undefined, :bool, :optional, []}, {:field, :push_to_talk, 3, :undefined, :bool, :optional, []}]}], [])
    lib/exprotobuf/parser.ex:25: Protobuf.Parser.parse!/2
    lib/exprotobuf.ex:55: Protobuf.parse/1
    expanding macro: Protobuf.__using__/1
    lib/opnd/mumble/protocol.ex:2: OPNd.Mumble.Protocol (module)
    (elixir) expanding macro: Kernel.use/2
    lib/opnd/mumble/protocol.ex:2: OPNd.Mumble.Protocol (module)
```

lib/opnd/mumble/protocol.ex:

```elixir
defmodule OPNd.Mumble.Protocol do
  use Protobuf, from: Path.expand("./Mumble.proto", __DIR__)
end
```

**Comment by eraserewind** [comment] 2015-01-08 14:29
It also fails when using the first example from the README:

```
== Compilation error on file lib/opnd/mumble/protocol.ex ==
** (UndefinedFunctionError) undefined function: :gpb_parse.post_process/2
    :gpb_parse.post_process([{{:msg, :Msg}, [{{:msg, :SubMsg}, [{:field, :value, 1, :undefined, :uint32, :required, []}]}, {{:enum, :Version}, [V1: 1, V2: 2]}, {:field, :version, 2, :undefined, {:ref, [:Version]}, :required, []}, {:field, :sub, 1, :undefined, {:ref, [:SubMsg]}, :optional, []}]}], [])
    lib/exprotobuf/parser.ex:25: Protobuf.Parser.parse!/2
    lib/exprotobuf.ex:55: Protobuf.parse/1
    expanding macro: Protobuf.__using__/1
    lib/opnd/mumble/protocol.ex:2: OPNd.Mumble.Test (module)
    (elixir) expanding macro: Kernel.use/2
    lib/opnd/mumble/protocol.ex:2: OPNd.Mumble.Test (module)
```

```elixir
defmodule OPNd.Mumble.Test do
  use Protobuf, """
    message Msg {
      message SubMsg {
        required uint32 value = 1;
      }

      enum Version {
        V1 = 1;
        V2 = 2;
      }

      required Version version = 2;
      optional SubMsg sub = 1;
    }
  """
end
```

**Comment by bitwalker** [comment] 2015-01-08 20:35
Taking a look now, I'd guess an upgrade of `gpb` broke this, I'll report back once I have a fix.

**Comment by bitwalker** [comment] 2015-01-08 20:52
Ok after attempting to replicate this, I'm unable to do so. I pushed some additional tests to master, could you pull `exprotobuf` separately, fetch deps, then run the tests? I'd like to narrow down what the cause is.

**Comment by eraserewind** [comment] 2015-01-09 12:15
Well... it works now :/ With a separate pull of `exprotobuf` and in my project. :confused:

**Comment by bitwalker** [comment] 2015-01-09 18:29
Huh, that's bizarre. Not sure what might have caused that, but I'll close this for now, feel free to reopen it if you run into this again and we can try and reproduce it somehow.

**Closed by bitwalker** 2015-01-09 18:29 UTC
Labels: bug

**Comment by davebryson** [comment] 2015-01-13 02:38
I'm having the same exact problem.  Pulling your code base and running the tests works fine.  But trying even your simple examples in a separate projects fails with the error mentioned above.  I even attempted to pull the dep for exprotobuf directly from github:
 
    defp deps do
      [{:exprotobuf, github: "bitwalker/exprotobuf"},
      {:gpb, github: "tomas-abrahamsson/gpb"}}
    end

Still having the same problem.  Any ideas?

**Comment by davebryson** [comment] 2015-01-13 02:48
It appears gdb no longer has the `:gdb_parse:post_process` .  According to the latest source here's the definition now:

    -module(gpb_parse).
    -export([parse/1, parse_and_scan/1, format_error/1]).
    -file("src/gpb_parse.yrl", 279).
    -include_lib("eunit/include/eunit.hrl").
    -include("../include/gpb.hrl").
    -export([post_process_one_file/2]).
    -export([post_process_all_files/2]).
    -export([format_post_process_error/1]).
    -export([fetch_imports/1]).

Am I missing something or is this the issue?  But why would it pass in your test cases?

**Comment by davebryson** [comment] 2015-01-13 03:01
So the issue is with the latest commit of gdb.  As I mentioned above gdb has changed the function naming.   If I use the same gdb commit number in mine mix.lock for gdb as you're using it works.

    {:git, "git://github.com/tomas-abrahamsson/gpb.git", "a6da429e3f433b958ae4f2806db57cd6451afb05",[]}

**Comment by bitwalker** [comment] 2015-01-14 19:02
Ah, makes sense. I'll dig into the `gpb` source and figure out what I need to do to migrate to the latest code. In the meantime I'll add a sha1 to the dep definition so that it's not just pulling the latest version every time. I would've expected the mix.lock to be honored, but I guess that's not the case.

**Comment by mr-bt** [comment] 2015-06-17 11:23
Hi,

Just bumped into this today when updating from 0.8.5 to 0.9.0. 

Here is my fix
brfore:
def parse(defs, options) when is_list(defs), do: :gpb_parse.post_process(defs, options)

after:
  def parse(defs, options) when is_list(defs) do
    {:ok, defs} = :gpb_parse.post_process_one_file(defs, options)
    :gpb_parse.post_process_all_files(defs, options)
  end

@bitwalker do you want me to make a pull request?

**Comment by bitwalker** [comment] 2015-06-17 14:44
@mr-bt Thanks for the PR! I'll push a new release today.
