### ISSUE TITLE
"warning: this clause cannot match" with elixir 1.4.4

### ISSUE THREAD

**Issue by burmajam** [bitwalker/exprotobuf#69] opened 2017-06-08 10:02 UTC
Hi,

*warning: this clause cannot match because a previous clause at line 1 always matches   lib/messages.ex:1* appears when compiling with Elixir 1.4.4. With 1.4.2 there's no such message.

lib/messages.ex contains only:

    defmodule Extreme.Msg do
      use Protobuf, from: Path.expand("../include/event_store.proto", __DIR__)
    end

and event_store.proto file is: https://github.com/exponentially/extreme/blob/master/include/event_store.proto

It looks as **enum** definition causes this warning. (there are 11 of them for this file). Do you have any idea what's wrong?

Thanks

**Comment by kenbod** [comment] 2017-06-17 20:28
I can confirm that I'm experiencing the same "issue". I put issue in quotes because it appears that this is just a weird compilation artifact. The warning gets generated but my application still builds and appears to work fine.

The file that generates the warning is simply:

```
defmodule Fixr.Features do
  use Protobuf, from: Fixr.proto
end
```

and Fixr.proto is just an absolute path name to a .proto file that is pulled from my configuration file in config/dev.exs.

The contents of the .proto file is:

```
syntax = "proto2";

package feature;

message BatchRequest {
   repeated SingleRequest requests = 1;
}

message SingleRequest {
   required string fileName = 1;
   required string sourceCode = 2;
}

message BatchResponse {
   repeated SingleResponse responses = 1;
}

message SingleResponse {
   enum Result {SUCC=1; FAIL=2; };

   required Result result = 1;
   required string fileName = 2;
 
   optional Features allFeatures = 3;
   optional ExtractError extractError = 4;
}

message ExtractError {
  required string error = 1;
  optional string err_class = 2; 
}

message Features {
  repeated Feature features = 1;
}

message Feature
{
  enum Type {CALLSITE=1; IMPORT=2; COMMENT=3; };
  // identifies which field is filled
  required Type featType = 1;

  optional Callsite callsite = 2;
  optional Import importFeature = 3;
  optional Comment comment = 4;
}

message Callsite {
  required string name = 1; // Name of the called method (e.g. method if t.method(...))

  required Expression expression = 2; // (Expression, type) used to call the method (e.g. t if t.method(...))
  repeated Expression args = 3; // List of (expr, type) arguments used to call the methods

  message Expression {
    optional string expressionName = 1; // an expression
    optional string expressionType = 2; // the type of the expression (can be null)
  }
  
  // List of contexts (ordered from the outer to the inner context)
  repeated Context contexts = 4;
}

message Import
{
  required string importName = 1; // List of imports of the program
}

message Comment
{
  enum Type {LINE=1; BLOCK=2; JAVADOC=3; };
  required Type commentType = 1; // identifies which field is filled

  required string text = 2; // text of the comment
}

// Represent a context
message Context
{
  enum Type {Class=1; Interface=2; AnonClass=3; Method=4; };
  optional Type contextType = 1;
  optional string name = 2; 
}
```

Hope this helps.

**Comment by bitwalker** [comment] 2017-06-22 18:15
A fix for this has been merged and will go out in the next release

**Closed** 2017-06-22 18:15 UTC
