### ISSUE TITLE
Problems with building release in project including exprotobuf

### ISSUE THREAD

**Issue by rafal-radziszewski** [bitwalker/exprotobuf#33] opened 2015-11-26 14:34 UTC
Some change that occured after commit 58f5d44 causes mix release task (exrm version 0.19.9) to fail on building tar archive. Issue has been narrowed down to exprotobuf in current HEAD. After reverting to mentioned commit everything started to work again.

**Comment by bitwalker** [comment] 2015-11-27 18:05
Is this resolved after #34 was merged?

**Comment by rafal-radziszewski** [comment] 2015-11-29 10:49
Nope, problem here stands. Here is the trace:

```
==> Generating release...
{{case_clause,
     {'EXIT',
         {function_clause,
             [{filename,join,[[]],[{file,"filename.erl"},{line,393}]},
              {erl_tar,split_filename,4,[{file,"erl_tar.erl"},{line,471}]},
              {erl_tar,create_header,3,[{file,"erl_tar.erl"},{line,400}]},
              {erl_tar,add1,4,[{file,"erl_tar.erl"},{line,323}]},
              {systools_make,add_to_tar,3,
                  [{file,"systools_make.erl"},{line,1879}]},
              {lists,foreach,2,[{file,"lists.erl"},{line,1337}]},
              {systools_make,'-add_applications/5-fun-0-',6,
                  [{file,"systools_make.erl"},{line,1569}]},
              {lists,foldl,3,[{file,"lists.erl"},{line,1262}]}]}}},
 [{systools_make,'-add_applications/5-fun-0-',6,
      [{file,"systools_make.erl"},{line,1569}]},
  {lists,foldl,3,[{file,"lists.erl"},{line,1262}]},
  {systools_make,add_applications,5,[{file,"systools_make.erl"},{line,1568}]},
  {systools_make,mk_tar,6,[{file,"systools_make.erl"},{line,1562}]},
  {systools_make,mk_tar,5,[{file,"systools_make.erl"},{line,1538}]},
  {systools_make,make_tar,2,[{file,"systools_make.erl"},{line,336}]},
  {rlx_prv_archive,make_tar,3,[{file,"src/rlx_prv_archive.erl"},{line,83}]},
  {relx,run_provider,2,[{file,"src/relx.erl"},{line,308}]}]}
==> Failed to build release. Please fix any errors and try again.
```

**Comment by bitwalker** [comment] 2015-11-30 16:09
@rafal-radziszewski I can't reproduce this with a new project. Could you share your mix.exs and how you are invoking the release task?

**Comment by mingchuno** [comment] 2016-02-20 16:30
This related issue may help
https://github.com/bitwalker/exrm/issues/299

**Comment by bitwalker** [comment] 2016-09-12 20:45
Closing this as it's a hard limit imposed on us by `systools` when unpacking releases. Further work on fixing this in the future will be handled via the exrm/distillery projects.

**Closed by bitwalker** 2016-09-12 20:45 UTC
