### ISSUE TITLE
Handling imports

### ISSUE THREAD

**Issue by kwojtaszek** [bitwalker/exprotobuf#21] opened 2015-08-15 21:56 UTC
We have defined a base.proto file:
```
package chat;

option java_package = "com.appunite.chat";

import "authorization.proto";

// From server to client
message WebsocketServerContainer {
      required authorization.AuthorizationServerMessage authorization = 1;
}
```
also additional file authorization.proto file:
```
package authorization;

option java_package = "com.appunite.chat";

// Message that is sent via server if authorization fail (sent via HTTP)
message WrongAuthorizationHttpMessage {
	required string reason = 1; // reason why authorization fail
}

// Message that is sent via server if authorization fail
message AuthorizationServerMessage {
	required string next_synchronization_token = 1; // token that should be sent to server next time synchronization occure
}
```

It looks like exprotobuf doesn't support for imports at all, because on compilation time it returns:
```
** (ArgumentError) argument error
    :erlang.byte_size([ref_to_undefined_msg_or_enum: {{[:., :WebsocketServerContainer], :authorization}, [:authorization, :., :AuthorizationServerMessage]}])
    (elixir) lib/exception.ex:106: Exception.format_banner/3
    (elixir) lib/exception.ex:141: Exception.format/3
    (elixir) lib/kernel/parallel_compiler.ex:216: Kernel.ParallelCompiler.print_failure/2
    (elixir) lib/kernel/parallel_compiler.ex:189: Kernel.ParallelCompiler.handle_failure/5
    (elixir) lib/kernel/parallel_compiler.ex:182: Kernel.ParallelCompiler.wait_for_messages/8
    (elixir) lib/kernel/parallel_compiler.ex:55: Kernel.ParallelCompiler.spawn_compilers/3
    (mix) lib/mix/compilers/elixir.ex:112: Mix.Compilers.Elixir.compile_manifest/5
```

**Comment by bitwalker** [comment] 2015-08-17 20:56
@kwojtaszek This is now working in master, could you test and verify on your end?

**Comment by bitwalker** [comment] 2015-08-17 20:57
Also I added tests in `test/protobuf/parse_test.exs` and `test/protobuf/import_test.exs` if you want to see how I'm testing the implementation.

**Comment by kwojtaszek** [comment] 2015-08-17 20:57
@bitwalker sure, will do it

**Comment by rafal-radziszewski** [comment] 2015-08-20 14:40
I checked it. Imports work, but there is a problem with namespacing - all imports reside in global namespace, which probably (I'm not sure yet) makes it incompatible with protobuf library definitions.

**Comment by dokie** [comment] 2015-08-27 22:20
I'm also bumping into this issue. The problem with the test case is that imports.proto doesn't make use of imported.proto. If we make the imports.proto
```protobuf
package chat;

option java_package = "com.appunite.chat";

import "imported.proto";

// From server to client
message WebsocketServerContainer {
      required string authorization = 1;
      required authorization.AuthorizationServerMessage msg = 2;
}
```
The mix test yields
```
** (Protobuf.Parser.ParserError) Reference to undefined message or enum authorization.AuthorizationServerMessage at WebsocketServerContainer.msg
    (exprotobuf) lib/exprotobuf/parser.ex:46: Protobuf.Parser.parse!/2
    (exprotobuf) lib/exprotobuf.ex:66: Protobuf.parse/2
    (exprotobuf) expanding macro: Protobuf.__using__/1
    test/protobuf/import_test.exs:5: Protobuf.Import.Test.WebsocketServerContainer (module)
    (elixir) expanding macro: Kernel.use/2
    test/protobuf/import_test.exs:5: Protobuf.Import.Test.WebsocketServerContainer (module)
```

**Comment by rafal-radziszewski** [comment] 2015-08-27 22:24
@dokie Actually, it is only namespacing issue. If you just change
`authorization.AuthorizationServerMessage` to `AuthorizationServerMessage` it works just fine. Packages do not take part in namespacing, the definitions are just copy-pasted in the place of import. The good thing is, that it does not create problem with binaries - I checked it encoding message with protoc compiled python files - reading with Elixir succeeded.

**Comment by dokie** [comment] 2015-08-27 22:32
I know, thanks for the reply. I cannot get my particular imported proto files to compile, even if I don't care about the namespacing.
**common.proto**
```protobuf
message Timestamp {
  required uint32 megaseconds = 1;
  required uint32 seconds = 2;
  required uint32 microseconds = 3;
}

message Angle {
  required sint32 degrees = 1;
  required sint32 minutes = 2;
  required float seconds = 3;
}
```

Used in other proto file, location_coordinates.proto
```protobuf
import "common.proto";

message LocationCoordinates {
  required Angle latitude = 1;
  required Angle longitude = 2;
  optional float altitude = 3 [default = 0.0];
  optional string datum = 4 [default = "wgs84"];
}
```

This yields the following error which I can't quite follow:
```
== Compilation error on file lib/location_coordinates.ex ==
** (Protobuf.Parser.ParserError) got [ref_to_undefined_msg_or_enum: {{[:., :LocationCoordinates], :latitude}, [:Angle]}, ref_to_undefined_msg_or_enum: {{[:., :LocationCoordinates], :longitude}, [:Angle]}] while retrieving Exception.message/1 for %Protobuf.Parser.ParserError{message: [ref_to_undefined_msg_or_enum: {{[:., :LocationCoordinates], :latitude}, [:Angle]}, ref_to_undefined_msg_or_enum: {{[:., :LocationCoordinates], :longitude}, [:Angle]}]} (expected a string)
    lib/exprotobuf/parser.ex:30: Protobuf.Parser.parse!/2
    lib/exprotobuf.ex:60: Protobuf.parse/1
    expanding macro: Protobuf.__using__/1
    lib/location_coordinates.ex:6: Tribune.Common.LocationCoordinates (module)
    (elixir) expanding macro: Kernel.use/2
    lib/location_coordinates.ex:6: Tribune.Common.LocationCoordinates (module)
```

Any help would be great.

**Comment by rafal-radziszewski** [comment] 2015-08-27 22:37
Could you possibly show directory structure? If I had to guess, I would say that imported file is in different directory.

**Comment by dokie** [comment] 2015-08-27 22:42
```
lib
   |--- location_coordinates.ex
protobuf
   |--- common.proto
   |--- location_coordinates.ex
```

where location_coordinates.ex has
```elixir
defmodule Tribune.Common.LocationCoordinates do
  @moduledoc """
  This represents the coordinates of a geographical location.
  See https://en.wikipedia.org/wiki/Geodetic_datum for more details.
  """
  use Protobuf, from: Path.expand("../protobuf/location_coordinates.proto", __DIR__), inject: true
...
```

**Comment by rafal-radziszewski** [comment] 2015-08-27 22:46
In that case, I would say the inject is the problem. The definition gets pulled into current module, and there is no place to put the one that is imported.

**Comment by dokie** [comment] 2015-08-27 22:51
So a bug in the handling of import in conjunction with inject then? If so I'll submit an issue and include my files, then fork and try to resolve over the next few days.

**Comment by rafal-radziszewski** [comment] 2015-08-27 22:56
I'm not sure if you can call it a bug. If you inject the definition of the message, your current module basically defines a struct in-place (as far as I understand it, I'm Elixir newbie). I don't see where should be imported message put. In your case, I would change the module you import protobuf in to `Tribune.Common`. Then you would have access to `Tribune.Common.LocationCoordinates`, `Tribune.Common.Timestamp` and  `Tribune.Common.Angle`. When you import it in module named after struct, the imported definitions need to go somewhere. You could namespace them from injection point, but I'm not sure if that is desired default behaviour. And if you put them one step higher, you encounter a problem if module you're working on is top-domain.

**Comment by dokie** [comment] 2015-08-27 23:01
OK, thanks. I'm going to look a bit harder at refactoring the code.

It should inject the importing proto as the struct of the module, but as you say, I can't therefore see why the imported proto (which should be transformed to a struct) does not just get injected in the module too.

**Comment by rafal-radziszewski** [comment] 2015-08-27 23:30
Because inject makes name of the module name of the structure defined in proto and the two are indistinguishable since (or do they need to be named the same? example is not clear). As far as I know, Elixir allows for one struct to be defined within the module. Other definitions would have to either be nested (as I said, probably not the best default behaviour) or put somewhere else. I believe injection is unnecessary if you have more than one proto, especially, that you namespace it anyway.

**Comment by DylanGriffith** [comment] 2015-08-31 10:19
Is there likely going to be a fix for the original issue here? I'm having problems too with my existing protobufs. I need my imports to take the package namespace. I figure out a way to hack the package namespace into the main message handing but it doesn't work with imports. I suppose more generally is there likely to be support added for the package namespace? We have a tonne of existing messages which all use the package so I will need that to work for compatibility.

**Comment by rafal-radziszewski** [comment] 2015-08-31 11:03
Just to be clear - if you remove namespaces there is a binary compatibility. The problem is, that you need to maintain different proto files for elixir (with namespacing removed).

**Comment by DylanGriffith** [comment] 2015-08-31 23:37
@rafal-radziszewski understood, but unfortunately maintaining multiple proto files is not an option for us. We have a tonne of existing proto files which make use of `package` and they would all need to be updated to somehow (probably manually) to even get them to compile. Then with the duplicate files we would end up missing out on a common communication language. I've actually figured out that packages can be made work with the [gpb use_packages option](https://github.com/tomas-abrahamsson/gpb/blob/5e04117cd55e51df75b9b8867e5e062a8e5dc39d/src/gpb_compile.erl#L278).

I'm starting to work on some fixes that I need for my work in a fork [here](https://github.com/bitwalker/exprotobuf/compare/master...DylanGriffith:dgvz) . There are quite a few changes there but actually the package stuff really only requires (I think) a change to the parser opts:

```diff
-    opts      = [imports: [path]]
+    opts      = [imports: [path], use_packages: true]
```

**Comment by bitwalker** [comment] 2015-10-01 22:04
@DylanGriffith Things have been really crazy the past month or so for me, so I haven't had a chance to look into this, but thanks for tracking down that option, as soon as I get some free time I'll dive in!

**Comment by mmmries** [comment] 2015-11-17 15:22
The way we handle this issue in [our ruby library](https://github.com/ruby-protobuf/protobuf) is to run our generator on a whole directory of `.proto` files. That way we end up generating an entire namespace and anything that gets `import`ed will also have been generated.

I wonder if we could do something like:
```elixir
defmodule Atlas do
  use Protobuf, from: Path.expand("../definitions/atlas/**/*.proto", __DIR__)
end
```

In our use case `definitions/atlas` is also the `imports_dir` so it makes up an entire library of proto messages that can `import` one another and use those definitions.

**Comment by DylanGriffith** [comment] 2015-11-17 21:27
@mmmries Funnily enough I had the same requirements and I've gotten that working in [my branch](https://github.com/DylanGriffith/exprotobuf/tree/dgvz) . The problem is that I had to do so much hacking at it that the tests aren't passing anymore, mainly because I removed some features. At the moment it works like

```
defmodule Foo do
   use Protobuf, from: Path.expand("some/path/*.proto")
end
```

The generated modules keep their original namespacing (eg. they won't start with `Foo` in the example above).

I really haven't had time to fix the repo yet. But I can say that it works for that one use case. I intend to clean it up at some point so all tests are passing and behaviour is documented but I don't know if it will end up supporting some of the features that we're in the original version.

**Comment by mmmries** [comment] 2015-11-17 22:06
@DylanGriffith I'm glad I'm not just some crazy person using protobuf in a weird way!

I've been playing locally with the idea of adding support for this. And I think the easiest way to make it work would be for the `from` option to support receiving a list of files rather than just a single path. That way simple cases continue to work, but you and I can use `Path.wildcard` to target an entire directory of messages that share some namespace.

Do you think it makes more sense for the `wildcard` to be applied by the module that is `use`ing Protobuf, or have Protobuf run it?

**Comment by DylanGriffith** [comment] 2015-11-17 23:34
I don't actually know if `use` is the right way to do this at all, but then I don't know elixir well enough to know how to do it any other way. I just want some way to have every protobuf compiled and accessible. The one problem I had with `use` is that it only recompiles when the `.ex` file containing the using module is changed rather than when the .proto files change. 

As I said I'm not really all that experienced at elixir, but yeah you aren't some crazy person. For us we really need to compile everything because we treat protobufs as a common communication language we want accessible at all times and it doesn't make sense to compile just one and it also doesn't make sense for us to ignore the package namespace.

That being said your suggestion to use list of files would also work for us rather than the glob string. I did initially try and tackle this problem in such a way that made the library backwards compatible but ended up giving up after finding that I needed to change a tonne of things to make it work, but then maybe some more skilled elixirer can do it in a more elegant way. As I said my branch does currently work, but it is quite diverted from what was there to begin with and it's not backwards compatible.

**Comment by bitwalker** [comment] 2015-11-20 00:47
@DylanGriffith Just thinking about the recompilation issue: I think that's something fairly easily resolved, as I do something similar with my `conform` library and it's PEG file for the conf grammar. I'll have to code up my gut solution to see if it works.

**Comment by DylanGriffith** [comment] 2015-11-20 03:09
@bitwalker it would make me very happy to see a solution to that. If for whatever reason you can't find the time to work on that It would be great if you could point me in the direction of implementing that myself.

**Comment by mmmries** [comment] 2015-12-21 02:10
I think we can close this now based on the work for `1.0.0-rc1`

**Closed** 2015-12-29 20:54 UTC
Labels: bug, level:advanced
